// Question definitions for the onboarding flow.
// Each question maps to a field in the Firebase /brands/{slug}/ structure.

export const QUESTIONS = [
  {
    id: 'display_name',
    type: 'text',
    label: "What's your brand name?",
    placeholder: 'e.g. Hollywood Browzer',
    required: true,
    path: 'config.display_name',
  },
  {
    id: 'website',
    type: 'url',
    label: "What's your website?",
    placeholder: 'https://hollywoodbrowzer.com',
    required: false,
    path: 'config.website',
  },
  {
    id: 'instagram',
    type: 'text',
    label: "Your Instagram handle?",
    placeholder: '@hollywoodbrowzer',
    required: false,
    path: 'config.instagram',
    hint: "Leave blank if you don't have one.",
  },
  {
    id: 'category',
    type: 'text',
    label: "What category is your brand in?",
    placeholder: 'e.g. Beauty Tools, Specialty Coffee, Supplements',
    required: true,
    path: 'config.category',
  },
  {
    id: 'mission',
    type: 'textarea',
    label: "What problem does your brand solve?",
    placeholder: 'Tell us in one or two sentences what your brand does and who it helps.',
    required: true,
    path: 'config.mission',
  },
  {
    id: 'usp',
    type: 'textarea',
    label: "What makes you different from competitors?",
    placeholder: 'The one thing that sets you apart — be specific.',
    required: true,
    path: 'config.usp',
  },
  {
    id: 'icp',
    type: 'textarea',
    label: "Who is your ideal customer?",
    placeholder: 'e.g. Women 25–45 in the UK who want smooth skin at home without a salon visit.',
    required: true,
    path: 'config.icp',
  },
  {
    id: 'tagline',
    type: 'text',
    label: "Do you have a tagline or key phrase?",
    placeholder: 'e.g. "The OG dermaplaning tool"',
    required: false,
    path: 'config.tagline',
    hint: 'Leave blank if not sure.',
  },
  {
    id: 'tone',
    type: 'textarea',
    label: "How would you describe your brand's voice?",
    placeholder: 'e.g. Confident and witty. Talks to women who want results, not jargon. Never overly clinical.',
    required: false,
    path: 'config.tone',
  },
  {
    id: 'competitors',
    type: 'tags',
    label: "Who are your main competitors?",
    placeholder: 'Type a brand name and press Enter',
    required: false,
    path: 'config.competitor_brands',
  },
  {
    id: 'market',
    type: 'text',
    label: "What markets are you selling in?",
    placeholder: 'e.g. UK (primary), Germany, France',
    required: false,
    path: 'config.market',
  },
  {
    id: 'monthly_spend',
    type: 'number',
    label: "Roughly how much do you spend on Meta Ads per month?",
    placeholder: '5000',
    prefix: '£',
    required: false,
    path: 'config.monthly_spend',
    hint: 'Approximate is fine. This helps us calibrate benchmarks.',
  },
  {
    id: 'aesthetic_tagline',
    type: 'text',
    label: "Describe your visual style in a few words.",
    placeholder: 'e.g. Clean and minimal, Raw and authentic, Warm and domestic',
    required: false,
    path: 'art_direction.aesthetic_tagline',
    hint: 'Think about how your best content looks.',
  },
  {
    id: 'aesthetic_desc',
    type: 'textarea',
    label: "Tell us more about how your brand should look in ads.",
    placeholder: 'e.g. Natural light, real settings, not overly staged. Products in use, not floating on white.',
    required: false,
    path: 'art_direction.aesthetic_desc',
  },
  {
    id: 'colors',
    type: 'color_palette',
    label: "What are your brand colors?",
    required: false,
    path: 'art_direction.colors',
    hint: 'Add up to 5. You can add hex codes or just describe the colors.',
  },
  {
    id: 'product_images',
    type: 'image_upload',
    label: "Upload your hero product image.",
    required: false,
    path: 'products[0].heroImageUrl',
    hint: 'Clean shot of your main product. JPG or PNG, at least 800×800px.',
    multiple: false,
  },
  {
    id: 'product_name',
    type: 'text',
    label: "What's the name of your hero product?",
    placeholder: 'e.g. Hollywood Browzer Original',
    required: false,
    path: 'products[0].name',
  },
  {
    id: 'product_benefits',
    type: 'benefits',
    label: "List up to 3 key benefits of your hero product.",
    placeholder: ['Removes peach fuzz instantly', 'No irritation, no redness', 'Results last 3–4 weeks'],
    required: false,
    path: 'products[0].benefits',
  },
];

export const WELCOME = {
  heading: "Let's set up your brand.",
  subheading: "This takes about 5 minutes. We use your answers to build a creative strategy tailored to your brand — before we run a single ad.",
  cta: "Start",
};

export const THANKYOU = {
  heading: "You're all set.",
  subheading: "We'll review your answers and get back to you within 24 hours with next steps.",
};
